import {
  LucideProps,
  PlusCircle,
  X,
  Plus,
  Pencil,
  Trash2,
  Settings,
  Tag,
  ShoppingCart,
  Package,
  Users,
  FileText,
  CreditCard,
  BarChart2,
  LogOut,
  Home,
  Search,
  ShoppingBag,
  ChevronRight,
  ChevronLeft,
  Menu,
  Check,
  User,
  Percent,
  Gift,
} from "lucide-react"

export type IconProps = LucideProps

export const Icons = {
  logo: Package,
  close: X,
  add: Plus,
  plusCircle: PlusCircle,
  edit: Pencil,
  delete: Trash2,
  settings: Settings,
  tag: Tag,
  cart: ShoppingCart,
  product: Package,
  user: User,
  users: Users,
  invoice: FileText,
  payment: CreditCard,
  analytics: BarChart2,
  logout: LogOut,
  home: Home,
  search: Search,
  shoppingBag: ShoppingBag,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  check: Check,
  percent: Percent,
  gift: Gift,
} 